---
title: "Mapa Uso e Cobertura Mapbiomas"
author: "Karen - Uenf"
date: "2023-10-03"
output: html_document
---
#==============================================================================#
#          EXTENSÃO UNIVERSITÁRIA EM CIÊNCIAS CLIMÁTICAS E AMBIENTAIS          #
#          PROJETO 'PROCESSAMENTO E ANÁLISE DE DADOS AMBIENTAIS COM R'         #
#                        Contato: pexcca.lamet@uenf.br                         #
#                       https://linktr.ee/pexcca.lamet                         #
#==============================================================================#

#--------------------------MAPA - MAPBIOMA            -------------------------#
#                       Elaboração:                                            #
#           Revisão:                                                           #
#                      Script Atualizado em                                    #
#------------------------------------------------------------------------------#


# Fonte: Os dados do MapBiomas são públicos, abertos e gratuitos sob licença CC-BY-SA e mediante a referência da fonte observando o seguinte formato:"Projeto MapBiomas – Coleção Beta de Mapas Anuais de Cobertura e Uso da Terra do Brasil com 10 metros de resolução espacial".

# Bibliotecas (Pacotes) --------------------------------------------------------
## Para instalar e carregar as bibliotecas necessárias, use os comandos abaixo:

install.packages('sf')
install.packages('geobr')
install.packages('ggspatial')
install.packages('tidyverse')
install.packages('ggrepel')

#Carregando os pacotes 

library('sf')
library('geobr')
library('ggspatial')
library('tidyverse')
library('ggrepel')

# Importação dos dados --------------------------------------------------------#
# Vamos fazer o donwload de uma base de dados das camadas do site do Mapbiomas.org
#Primeiro, vamor criar uma pasta denominada 'data':

if(!dir.exists('data/'))
  dir.create('data')

#Agora, vamos fazer o download do arquivo zipado:
#download.file(url =

# Podemos usar a função read_country() para baixar os dados das fronteiras do Brasil.
BR <- geobr::read_country(year = 2020)   # 2020 é o ano do conjunto de dados. 
plot(BR$geom)
sf::st_crs(BR) 

# LINK DE ACESSO DADOS SHP
LINK: https://geoftp.ibge.gov.br/informacoes_ambientais/cobertura_e_uso_da_terra/uso_250mil/vetores/
  
  
# Produção do Mapa -------------------------------------------------------------  
AC <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/USO_AC_250.shp")
AM <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/USO_da_Terra_AM_250_000.shp") 
AP <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/AP_250.shp")
MA <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/MA_uso_250_13_05_16.shp")
MT <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/MT_250.shp")
PA <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/Para_250.shp")
RJ <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/Rio_de_Janeiro.shp")
RO <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/Rondonia_250000.shp")
RR <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/CoberturaUsoTerraRoraima_250.shp")
RS <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/RS_250MIL_FINAL.shp")
SE <- sf::st_read(dsn = "C:/Users/IMTT/Desktop/PASTA KAREN UENF/USO E COBERTURA/SE_Uso_terra_BDIA.shp")

# Transformação para o sistema de coordenadas SIRGAS 2000 (EPSG:4674)

sirgas_2000_epsg <- 4674
AC <- st_transform(AC, crs = sirgas_2000_epsg)
AM <- st_transform(AM, crs = sirgas_2000_epsg)
AP <- st_transform(AP, crs = sirgas_2000_epsg)
MA <- st_transform(MA, crs = sirgas_2000_epsg)
MT <- st_transform(MT, crs = sirgas_2000_epsg)
PA <- st_transform(PA, crs = sirgas_2000_epsg)
RJ <- st_transform(RJ, crs = sirgas_2000_epsg)
RO <- st_transform(RO, crs = sirgas_2000_epsg)
RR <- st_transform(RR, crs = sirgas_2000_epsg)
RS <- st_transform(RS, crs = sirgas_2000_epsg)
SE <- st_transform(SE, crs = sirgas_2000_epsg)

# MAPAS INICIAIS
library("ggrepel")

# Definindo cores para cada estado
estados <- c("AC", "AM", "AP", "MA", "MT", "PA", "RJ", "RO", "RR", "RS", "SE")
cores <- c("#4D5C12", "#7A8218", "#A0A235", "#BCC05D", "#D7D783", "#F0EDA9", "#B5B5B5", "#A3A3A3", "#919191", "#7F7F7F", "#6D6D6D")

#PREPARANDO O MAPA

mapa1 <- 
  ggplot() + 
  geom_sf(data = BR,
          fill = "beige",
          color = 'gray',
          size = 2) +
  #AC
  geom_sf(
    data= AC$geometry,
    mapping = aes(fill = "fill"),  
    alpha = 0.8,
    size = 4) + 
  
  #AM
  geom_sf(
    data = AM$geometry,
    mapping = aes(fill = "fill"),
    alpha = 0.6,
    size = 3
  ) +
  
  #AP 
  geom_sf(
    data = AP$geometry,
    mapping = aes(fill = "fill"),
    alpha = 0.7,
    size = 5
  ) +
  
  #MA
  geom_sf(
    data= MA$geometry,
    mapping = aes(fill = "fill"),
    alpha = 0.9,
    size = 6) +
  
  #MT
  geom_sf(
    data= MT$geometry,
    mapping = aes(fill = "fill"),
    alpha = 1.0,
    size = 7) +
  
  #PA
  geom_sf(
    data= PA$geometry,
    mapping = aes(fill = "fill"),
    alpha = 1.1,
    size = 8) +
  
  #RJ
  geom_sf(
    data= RJ$geometry,
    mapping = aes(fill = "fill"),
    alpha = 1.2,
    size = 9) +
    
    #RO
  geom_sf(
    data= RO$geometry,
    mapping = aes(fill = "fill"),
    alpha = 1.3,
    size = 10) +
  
  #RR
  geom_sf(
    data= RR$geometry,
    mapping = aes(fill = "fill"),
    alpha = 1.4,
    size = 11) +
  
    
    #RS
    geom_sf(
      data= RS$geometry,
      mapping = aes(fill = "fill"),
      alpha = 1.5,
      size = 12) +
    
    #SE
    geom_sf(
      data= SE$geometry,
      mapping = aes(fill = "fill"),
      alpha = 1.6,
      size = 13) +
      
  geom_label(
    mapping = aes(x = -65, y = -20, label = 'AC'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  ) +
  geom_label(
    mapping = aes(x = -55, y = -10, label = 'AM'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  ) +
  geom_label(
    mapping = aes(x = -40, y = -22, label = 'AP'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  ) +
  geom_label(
    mapping = aes(x = -40, y = -22, label = 'MA'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  )+
  geom_label(
    mapping = aes(x = -40, y = -22, label = 'MT'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  )+
  geom_label(
    mapping = aes(x = -40, y = -22, label = 'PA'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  )+
  geom_label(
    mapping = aes(x = -40, y = -22, label = 'RJ'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  )+
  geom_label(
    mapping = aes(x = -40, y = -22, label = 'RO'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  )+
  geom_label(
    mapping = aes(x = -40, y = -22, label = 'RR'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  )+
  geom_label(
    mapping = aes(x = -40, y = -22, label = 'RS'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3
  )+
  geom_label(
    mapping = aes(x = -40, y = -22, label = 'SE'),
    fill = '#FFFFFF',
    color = 'gray30',
    size = 7,
    alpha = 0.3) +
  
  # Informações das Coordenadas Geográficas:
  geom_label(
    mapping = aes(x = -58, y = -30),
    label = 'DATUM SIRGAS 2000 \n Sistema de Coordenadas Geográficas \n Fonte: IBGE (2019; 2020); Mapbiomas (2000,2010 e 2012) \n Elaborado por KAREN (@proamb.r)', 
    fill = '#FFFFFF',
    size = 4,
    alpha = 0.5
  ) +
  # Título
  labs(
    title = 'USO E COBERTURA DO SOLO MAPBIOMAS',
    # caption = info,
    x = NULL,
    y = NULL,
  ) +
  # Tema do plot:
  theme(
    plot.title =
      element_text(
        face = 'bold',
        size = 20,
        lineheight = 0.9,
        hjust = 0.5
      ),
    legend.position = 'none',
    legend.background = element_rect(fill = "#FFFFFF",
                                     linetype = "solid",
                                     colour = "#000000"),
    plot.caption = element_text(size = 10),
    panel.background = element_rect(fill = '#557E84'),
    panel.grid.major = element_line(
      colour = '#486C71',
      linetype = 'twodash'
    )
  ) +
  guides(fill = guide_legend(reverse = TRUE)) +
  # Limites x e y do plot:
  coord_sf(
    xlim = c(-73, -35),
    ylim = c(5, -34)
  ) +
# Escala gráfica:
  annotation_scale(
    location = 'bl',
    line_col = 'gray30',
    text_col = 'grey30',
    style = 'ticks',
    text_cex = 1,
    text_face = 'bold',
    line_width = 4
  ) +
  # Seta norte:
  annotation_north_arrow(
    location = 'tr',
    pad_x = unit(0.2, 'cm'),
    pad_y = unit(0.2, 'cm'),
    height = unit(2.0, 'cm'),
    width = unit(2.0, 'cm'),
    style = north_arrow_fancy_orienteering(
      fill = c('#A9A98F', '#F2F2E6'),
      line_col = 'grey30'
    )
  )
mapa1
